config/routes.rb
Rails.application.routes.draw do

  resources :styles
  resources :breweries
  resources :styles
  resources :breweries
  resources :beers

  root 'beers#index'
end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
  belongs_to :style

  mount_uploader :image, BeerUploader
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :beers
end

app/models/style.rb
class Style < ActiveRecord::Base
  has_many :beers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    @beers = Beer.all
  end

  def show
    @beer = Beer.find(params[:id])
  end

  def new
    @beer = Beer.new
  end

  def create
    @beer = Beer.new(beer_params)

    if @beer.save
     redirect_to @beer
    else
     render 'new'
    end
  end

  def edit
    @beer = Beer.find(params[:id])
  end

  def update
    @beer = Beer.find(params[:id])

    if @beer.update(beer_params)
    redirect_to @beer
    else
    render 'edit'
    end
  end

  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    redirect_to beers_path
  end

  private
  def beer_params
    params.require(:beer).permit(:name, :abv, :flavor, :color, :bubbly, :brewery_id, :style_id, :image)
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name)
    end
end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :set_style, only: [:show, :edit, :update, :destroy]

  # GET /styles
  # GET /styles.json
  def index
    @styles = Style.all
  end

  # GET /styles/1
  # GET /styles/1.json
  def show
  end

  # GET /styles/new
  def new
    @style = Style.new
  end

  # GET /styles/1/edit
  def edit
  end

  # POST /styles
  # POST /styles.json
  def create
    @style = Style.new(style_params)

    respond_to do |format|
      if @style.save
        format.html { redirect_to @style, notice: 'Style was successfully created.' }
        format.json { render :show, status: :created, location: @style }
      else
        format.html { render :new }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /styles/1
  # PATCH/PUT /styles/1.json
  def update
    respond_to do |format|
      if @style.update(style_params)
        format.html { redirect_to @style, notice: 'Style was successfully updated.' }
        format.json { render :show, status: :ok, location: @style }
      else
        format.html { render :edit }
        format.json { render json: @style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /styles/1
  # DELETE /styles/1.json
  def destroy
    @style.destroy
    respond_to do |format|
      format.html { redirect_to styles_url, notice: 'Style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_style
      @style = Style.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def style_params
      params.require(:style).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
  def brewery_id_select
    names = Brewery.all
      breweries_all = []

      names.each do |t|
        breweries_all << [t.name, t.id]

      end
      breweries_all
  end

  def style_id_select
    names = Style.all
      styles_all = []

      names.each do |t|
        styles_all << [t.name, t.id]

      end
      styles_all
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/styles_helper.rb
module StylesHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.label :abv %><br>
    <%= f.text_field :abv %>
  </p>

  <p>
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </p>

  <p>
    <%= f.label :flavor %><br>
    <%= f.text_field :flavor %>
  </p>

  <p>
    <%= f.label :bubbly %><br>
    <%= f.text_field :bubbly %>
  </p>

  <p>
    <%= f.label :brewery %><br>
  </p>
    <%= f.select :brewery_id, brewery_id_select,{}, class: "form-control" %>

  <p>
    <%= f.label :style %><br>
    <%= f.select :style_id, style_id_select,{}, class: "form-control" %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/beers/edit.html.erb
<h1>Edit beers </h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %>
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Beers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Image</th>
    <th>Abv</th>
    <th>Flavor</th>
    <th>Color</th>
    <th>Bubbly</th>
    <th>brewery</th>
    <th>Style</th>
    <th>Group</th>
  </tr>
<% @beers.each do |beer| %>

  <tr>
    <td><%= link_to beer.name, beer_path(beer.id) %></td>
    <td><%= image_tag(beer.image) %></td>
    <td><%= beer.abv %></td>
    <td><%= beer.flavor %></td>
    <td><%= beer.color %></td>
    <td><%= beer.bubbly %></td>
    <td><%= beer.brewery.name %></td>
    <td><%= beer.style.name %></td>
    <td><%= beer.group %></td>
    <td>
      <%= link_to " Delete ", beer, :method => :delete, :confirm => "Are you sure ?"%>
      <%= link_to ' Edit ', edit_beer_path(beer) %>
    </td>
  </tr>

<% end %>
</table>

  <br>

<%= link_to 'New', new_beer_path %>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h5>Name:</h5>
  <%= @beer.name %>
</p>

<p>
  <h5>image</h5>
  <%= image_tag(@beer.image) %>
</p>

<p>
  <h5>Abv:</h5>
  <%= @beer.abv %>
</p>

<p>
  <h5>Flavor:</h5>
  <%= @beer.flavor %>
</p>
<p>
  <h5>Color:</h5>
  <%= @beer.color %>
</p>
<p>
  <h5>Bubbly:</h5>
  <%= @beer.bubbly %>
</p>
<p>
  <h5>Brewery:</h5>
  <%= @beer.brewery.name %>
</p>
<p>
  <h5>Style:</h5>
  <%= @beer.style.name %>
</p>
<p>
  <h5>Group:</h5>
  <%= @beer.group %>
</p>

<%= link_to 'Back', beers_path %>

<p>
  <h5>RECOMENDACIONES:</h5>
</p>
<% Beer.where(group: "#{@beer.group}").each do |beer| %>

  <div>
    <%= link_to beer.name, beer_path(beer.id) %>
  </div>

<% end %>

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Breweries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @breweries.each do |brewery| %>
      <tr>
        <td><%= brewery.name %></td>
        <td><%= link_to 'Show', brewery %></td>
        <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
        <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brewery', new_brewery_path %>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brewery.name %>
</p>

<%= link_to 'Edit', edit_brewery_path(@brewery) %> |
<%= link_to 'Back', breweries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DrinkIt</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/styles/_form.html.erb
<%= form_for(@style) do |f| %>
  <% if @style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@style.errors.count, "error") %> prohibited this style from being saved:</h2>

      <ul>
      <% @style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/styles/edit.html.erb
<h1>Editing Style</h1>

<%= render 'form' %>

<%= link_to 'Show', @style %> |
<%= link_to 'Back', styles_path %>

app/views/styles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Styles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @styles.each do |style| %>
      <tr>
        <td><%= style.name %></td>
        <td><%= link_to 'Show', style %></td>
        <td><%= link_to 'Edit', edit_style_path(style) %></td>
        <td><%= link_to 'Destroy', style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Style', new_style_path %>

app/views/styles/new.html.erb
<h1>New Style</h1>

<%= render 'form' %>

<%= link_to 'Back', styles_path %>

app/views/styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @style.name %>
</p>

<%= link_to 'Edit', edit_style_path(@style) %> |
<%= link_to 'Back', styles_path %>